# -*- coding: utf-8 -*-
"""SAI_out-of-box_v201912.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19-3zZuya-5hrCPybmACgUy4Pqh1E0rHp

This notebook shows how to run a **SAI client on Google Colab's NVIDIA Tesla K80 GPU**. Thanks to [djinnome from GitHub who figured it out.](https://github.com/glinscott/leela-chess/issues/284).

Updated to work with NVIDIA driver 396.44.

Run each cell in order, waiting for the previous one to finish before running the next.

The scripts and cell layout may be messy/redundant, but this should work.
"""

import subprocess
if subprocess.run(["nvidia-smi", "-L"]).returncode != 0:
  assert False, "No GPU available!"

!rm -rf sai_in_colab
!git clone https://github.com/nanzi/sai_in_colab.git
!cd sai_in_colab && chmod +x sai autogtp
!cd sai_in_colab && git shortlog

"""Congratulations! We can contribute to SAI project by running code blocks below.Please replace $\$username$ and $\$passwd$ into yours，-m help you to limit selfplays number.

恭喜你！然后我们运行下面代码跑谱：请替换 $\$username$ 和 $\$passwd$为你的，修改 -m 参数可以设定跑谱数量上限。
"""

!cd sai_in_colab && ./autogtp --url http://sai.unich.it/ --username $username --password $passwd -m100| grep minute
